name: Code Coverage

on: 
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs: 
  CodeCov: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: Install modules
        run: pnpm install
      - name: Run Test Coverage
        run: cd packages/smarty-ui-vite && pnpm coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: packages/smarty-ui-vite/coverage
          token: ${{ secrets.CODECOV_TOKEN  }}